# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# our routing
proton_homepage:
    pattern: /
    defaults: { _controller: ProtonFrontendBundle:Frontend:index }

proton_tutorial:
    resource: "@ProtonTutorialBundle/Resources/config/routing.yml"

proton_question:
    resource: "@ProtonQnABundle/Resources/config/routing.yml"

proton_answer:
    resource: "@ProtonQnABundle/Controller/AnswerController.php"
    type: annotation

# 3rd-party routing

# fos_user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

# fos_comment
fos_comment:
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
