services:
    proton_tutorial.manager.tutorial:
        class: Proton\TutorialBundle\Entity\TutorialManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            redis: "@snc_redis.default_client"
            class: Proton\TutorialBundle\Entity\Tutorial
    proton_tutorial.blamer.tutorial.security:
        class: Proton\TutorialBundle\Blamer\SecurityTutorialBlamer
        arguments:
            securityContext: "@security.context"
    proton_tutorial.creator.tutorial:
        class: Proton\TutorialBundle\Creator\TutorialCreator
        arguments:
            tutorialManager: "@proton_tutorial.manager.tutorial"
            blamer: "@proton_tutorial.blamer.tutorial.security"
    proton_tutorial.form_type.tutorial:
        class: Proton\TutorialBundle\Form\TutorialType
        arguments:
            tagTransformer: "@proton_tag.form.transformer.tag"
        tags:
            - { name: form.type, alias: proton_tutorial_tutorial }
